name: 'Latino .NET Online: MeetupWebScraping'
description: 'Get 3 last meetup in Latino .NET Online´s Meetup Profile'
inputs:
  gh-token: 
    required: true
runs:
  using: 'node12'
  main: 'index.js'
