name: Meetup WebScraping

on:
  push:
    branches: [ main ]
    
  schedule: 
   # Cada 5 minutos. Igual ni funciona 🤷‍♂️
   - cron: '*/5 * * * *' 
   
  repository_dispatch:
    types: [MeetupWebScraping-Dispatch]
     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   
  job:
    name: Run Action
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Copy AivenWeb Packages
      run: cp -r offline-packages src/packages

    - name: Run Console
      run: dotnet run -c Release --project src/MeetupWebScraping/MeetupWebScraping.csproj -- -gh-token ${{ secrets.GHToken }}

