name: .NET Core Action Template

on:
  push:
    branches: [ main ]
    
  schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '0 * * * *' 
     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - uses: ./
      with:
        gh-token: ${{ secrets.GHToken }}
